name: Update GitHub Stats

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'
      - '.github/workflows/update-status.yml'

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update README with GitHub Stats
      run: |
        # Atualizando o README com informações reais ou estatísticas
        # Adicione aqui os comandos ou scripts necessários para gerar e atualizar o conteúdo do README.
        
        # Exemplo de atualização fictícia para demonstração
        echo "Atualizando status do repositório..." > README.md
        
        # Configuração do Git
        git config --global user.email "gabrielvieira.wks@gmail.com"
        git config --global user.name "Gabriel Vieira"
        
        # Adiciona e comita as mudanças
        git add README.md
        git commit -m "Atualizando status do repositório"
        
        # Força o push das mudanças
        git push
