name: Update README with GitHub Stats

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update README with GitHub Stats
      run: |
        # Atualize seu README.md com informações reais ou estatísticas
        # Exemplo fictício de atualização
        echo "Atualizando status do repositório..." > README.md
        
        # Configuração do Git
        git config --global user.email "gabrielvieira.wks@gmail.com"
        git config --global user.name "Gabriel Vieira"
        
        # Adiciona e comita as mudanças
        git add README.md
        git commit -m "Atualizando status do repositório" || echo "No changes to commit"
        
        # Push das mudanças usando o token do GitHub Actions
        git push
